# Kernel sources configuration
# Format: <phone> <name> <repo_url> <branch> <arch>
# <name> must match a config file in configs/<name>.config
fp2  msm8974-6.12.y  https://github.com/msm8974-mainline/linux  qcom-msm8974-6.12.y  arm
fp2  msm8x74-6.15.y  https://github.com/mlainez/linux-msm8x74   staging               arm
fp3  msm8953-staging  https://github.com/mlainez/linux-msm8953   staging               arm64
